"""New migration

Revision ID: 01a56b78f1ca
Revises: f458e21c4792
Create Date: 2021-03-06 14:27:48.725638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a56b78f1ca'
down_revision = 'f458e21c4792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
