"""make migration

Revision ID: 03b3ed081e85
Revises: 96afcac5fb92
Create Date: 2021-03-07 15:05:47.392321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b3ed081e85'
down_revision = '96afcac5fb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
