"""New migration

Revision ID: 16fd55ae0711
Revises: 01a56b78f1ca
Create Date: 2021-03-06 14:34:53.878593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fd55ae0711'
down_revision = '01a56b78f1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
