"""make migration

Revision ID: 1dae8c129450
Revises: 2441f6bf063c
Create Date: 2021-03-07 14:43:18.138033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dae8c129450'
down_revision = '2441f6bf063c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('microblog_posts_user_fkey', 'microblog_posts', type_='foreignkey')
    op.drop_column('microblog_posts', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('microblog_posts_user_fkey', 'microblog_posts', 'user', ['user'], ['id'])
    # ### end Alembic commands ###
