"""make migration

Revision ID: 202a2000683f
Revises: 6494c6b351ea
Create Date: 2021-03-08 10:48:11.797411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202a2000683f'
down_revision = '6494c6b351ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
