"""make migration

Revision ID: 2441f6bf063c
Revises: f165e1c6ef35
Create Date: 2021-03-07 14:40:05.039862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2441f6bf063c'
down_revision = 'f165e1c6ef35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Date')
    # ### end Alembic commands ###
