"""make migration

Revision ID: 31ff994fe4cf
Revises: 16fd55ae0711
Create Date: 2021-03-06 14:35:54.872488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ff994fe4cf'
down_revision = '16fd55ae0711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microblog_posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
