"""First

Revision ID: 417770bad6c3
Revises: abbcf56e728f
Create Date: 2021-03-06 11:57:08.750409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417770bad6c3'
down_revision = 'abbcf56e728f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
