"""New migration

Revision ID: 4254c7fb460d
Revises: f4a6bea10255
Create Date: 2021-03-06 15:00:24.971324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4254c7fb460d'
down_revision = 'f4a6bea10255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
