"""second

Revision ID: 471d97fdaa8a
Revises: 417770bad6c3
Create Date: 2021-03-06 11:58:11.394056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471d97fdaa8a'
down_revision = '417770bad6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
