"""New migration

Revision ID: 50d26049d282
Revises: 571ba44b7c92
Create Date: 2021-03-06 12:17:17.053737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d26049d282'
down_revision = '571ba44b7c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
