"""newSecond

Revision ID: 5c41a16a31e4
Revises: f5dd55e02110
Create Date: 2021-02-13 20:00:48.283544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c41a16a31e4'
down_revision = 'f5dd55e02110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('newString', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microblog_posts', 'newString')
    # ### end Alembic commands ###
