"""make migration

Revision ID: 6494c6b351ea
Revises: 71d4795467a5
Create Date: 2021-03-08 10:47:28.271279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6494c6b351ea'
down_revision = '71d4795467a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
