"""New migration

Revision ID: 6ca59dee33f1
Revises: 2a6856902578
Create Date: 2021-03-07 13:30:15.874965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca59dee33f1'
down_revision = '2a6856902578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
