"""make migration

Revision ID: 8b2e3b08b57f
Revises: 31ff994fe4cf
Create Date: 2021-03-06 14:38:07.451260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2e3b08b57f'
down_revision = '31ff994fe4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microblog_posts', 'title')
    # ### end Alembic commands ###
