"""new model

Revision ID: abbcf56e728f
Revises: 5e11e1e98a7e
Create Date: 2021-02-14 14:39:12.646920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbcf56e728f'
down_revision = '5e11e1e98a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('microblog_posts_user_id_fkey', 'microblog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'microblog_posts', 'user', ['user'], ['id'])
    op.drop_column('microblog_posts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'microblog_posts', type_='foreignkey')
    op.create_foreign_key('microblog_posts_user_id_fkey', 'microblog_posts', 'user', ['user_id'], ['id'])
    op.drop_column('microblog_posts', 'user')
    # ### end Alembic commands ###
