"""New migration

Revision ID: bfe556075a23
Revises: 4254c7fb460d
Create Date: 2021-03-06 15:03:11.013513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe556075a23'
down_revision = '4254c7fb460d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
