"""make migration

Revision ID: f165e1c6ef35
Revises: 6ca59dee33f1
Create Date: 2021-03-07 14:28:23.697274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f165e1c6ef35'
down_revision = '6ca59dee33f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
