"""New migration

Revision ID: f458e21c4792
Revises: 50d26049d282
Create Date: 2021-03-06 12:18:53.786751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f458e21c4792'
down_revision = '50d26049d282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
