"""new

Revision ID: f5dd55e02110
Revises: a3e05de1cafe
Create Date: 2021-02-13 19:56:35.096083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dd55e02110'
down_revision = 'a3e05de1cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
